// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id)
VALUES ($1)
RETURNING id, customer_id, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(&i.ID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_cents)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price_cents
`

type CreateOrderItemParams struct {
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int32 `json:"quantity"`
	PriceCents int32 `json:"price_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceCents,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    price_cents,
    quantity
)
VALUES (
    $1, $2, $3
)
RETURNING id, name, price_cents, quantity, created_at
`

type CreateProductParams struct {
	Name       string `json:"name"`
	PriceCents int32  `json:"price_cents"`
	Quantity   int32  `json:"quantity"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.Name, arg.PriceCents, arg.Quantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const findProductByID = `-- name: FindProductByID :one
SELECT id, name, price_cents, quantity, created_at
FROM products
WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_cents, quantity, created_at
FROM products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceCents,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductName = `-- name: UpdateProductName :exec
UPDATE products
SET name = $1
WHERE id = $2
RETURNING id, name, price_cents, quantity, created_at
`

type UpdateProductNameParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateProductName(ctx context.Context, arg UpdateProductNameParams) error {
	_, err := q.db.Exec(ctx, updateProductName, arg.Name, arg.ID)
	return err
}

const updateQuantityProductByID = `-- name: UpdateQuantityProductByID :execrows
UPDATE products
SET quantity = quantity-$1
WHERE id = $2
    AND quantity >= $1
`

type UpdateQuantityProductByIDParams struct {
	Quantity int32 `json:"quantity"`
	ID       int64 `json:"id"`
}

func (q *Queries) UpdateQuantityProductByID(ctx context.Context, arg UpdateQuantityProductByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateQuantityProductByID, arg.Quantity, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
